export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const NEWS_ROUTE = '/news'
export const NEWS_ROUTE_SINGLE = '/news/:id'
export const PROFILE_ROUTE = '/profile'